services:
  - type: web
    name: pulse-docs
    env: node
    plan: free
    buildCommand: cd docs && npm install
    startCommand: cd docs && npm run start
    envVars:
      - key: NODE_VERSION
        value: 22
