services:
  - type: web
    name: pulse-docs
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run docs:start
    envVars:
      - key: NODE_VERSION
        value: 22
    headers:
      - path: /pulse-ui.css
        name: Cache-Control
        value: public, immutable, max-age=31536000
      - path: /theme.css
        name: Cache-Control
        value: public, immutable, max-age=31536000
      - path: /docs.css
        name: Cache-Control
        value: public, immutable, max-age=31536000
      - path: /home-brut.css
        name: Cache-Control
        value: public, immutable, max-age=31536000
